# Generated by Django 6.1.1 on 2026-09-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_trip_selected_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, help_text="e.g., 'Historical Exploration'", max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the time of day')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary.dailyplan')),
            ],
            options={
                'ordering': ['time_of_day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trips.trip')),
            ],
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itinerary.itinerary'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('itinerary', 'day_number')},
        ),
    ]
