# Generated by Django 6.1.1 on 2026-09-21 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('food_preferences', models.JSONField(blank=True, default=list)),
                ('accommodation_type', models.JSONField(blank=True, default=list)),
                ('travel_style', models.CharField(blank=True, max_length=50)),
                ('activity_intensity', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trip')},
            },
        ),
    ]
