# Generated by Django 6.1.1 on 2026-09-22 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum acceptable total trip spend (INR or trip currency)', max_digits=10, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum the user is willing to spend', max_digits=10, null=True)),
                ('travel_style', models.CharField(choices=[('budget', 'Budget Backpacker'), ('mid_range', 'Mid Range'), ('luxury', 'Luxury')], default='mid_range', max_length=20)),
                ('preferred_transport', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('road', 'Road Trip (Car/Bike)'), ('any', 'No Preference')], default='any', max_length=20)),
                ('max_travel_hours', models.PositiveIntegerField(blank=True, help_text='Maximum hours willing to travel (one way)', null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('diet_type', models.CharField(default='non_vegetarian', max_length=20)),
                ('food_allergies', models.JSONField(blank=True, default=list, help_text="List of allergy strings e.g. ['nuts', 'gluten']")),
                ('accommodation_type', models.CharField(choices=[('hostel', 'Hostel'), ('budget', 'Budget Hotel'), ('mid_range', 'Mid-Range Hotel'), ('luxury', 'Luxury Hotel / Resort'), ('apartment', 'Apartment / Airbnb')], default='mid_range', max_length=20)),
                ('activity_intensity', models.CharField(choices=[('relaxed', 'Relaxed (minimal exertion)'), ('moderate', 'Moderate (some walking/activity)'), ('adventurous', 'Adventurous (high activity)')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_preferences', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Preference',
                'verbose_name_plural': 'Member Preferences',
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
