# Generated by Django 6.1.1 on 2026-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(default='India', max_length=100)),
                ('region', models.CharField(blank=True, help_text='State / geographic region', max_length=100)),
                ('description', models.TextField()),
                ('estimated_daily_cost_min', models.PositiveIntegerField(help_text='Minimum estimated per-person daily cost (INR)')),
                ('estimated_daily_cost_max', models.PositiveIntegerField(help_text='Maximum estimated per-person daily cost (INR)')),
                ('tags', models.JSONField(default=list, help_text='Interest tags matching preference interests vocabulary')),
                ('popular_activities', models.JSONField(default=list, help_text='List of activity name strings')),
                ('best_for_intensity', models.CharField(choices=[('relaxed', 'Relaxed'), ('moderate', 'Moderate'), ('adventurous', 'Adventurous')], default='moderate', max_length=20)),
                ('travel_difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('recommended_seasons', models.JSONField(default=list, help_text='List of best-visit month numbers (1=Jan … 12=Dec)')),
                ('typical_duration_days_min', models.PositiveIntegerField(default=3)),
                ('typical_duration_days_max', models.PositiveIntegerField(default=7)),
                ('approximate_travel_hours_from_metro', models.FloatField(blank=True, help_text='Approximate one-way travel time by common transport from nearest major metro (hours)', null=True)),
                ('reachable_by', models.JSONField(default=list)),
                ('accommodation_available', models.JSONField(default=list)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Unsplash or CDN URL for destination card image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
    ]
